[project]
name = "stratum-db"
version = "0.1.0"
dependencies = [
    "sortedcontainers",
    "sqlalchemy",
    "psycopg[binary]",
    "grpcio",
    "grpcio-tools",
]

[tool.pytest.ini_options]
pythonpath = ["."]
markers = [
	"timeout(seconds): mark test to fail if it exceeds the given number of seconds"
]