[project]
name = "stratum-db"
version = "0.1.0"
dependencies = [
    "sortedcontainers",
]

[project.optional-dependencies]
metadata = ["sqlalchemy", "psycopg[binary]"]
server = ["grpcio", "grpcio-tools", "python-dotenv"]

[tool.setuptools.packages.find]
include = ["stratum*"]

[tool.pytest.ini_options]
pythonpath = ["."]
markers = [
	"timeout(seconds): mark test to fail if it exceeds the given number of seconds"
]